# Generated by Django 5.2.1 on 2025-05-15 11:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_celery_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('original_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное имя файла')),
                ('file_path', models.CharField(max_length=1024, verbose_name='Путь к сохраненному файлу')),
                ('status', models.CharField(choices=[('PENDING', 'В очереди'), ('STARTED', 'Запущена'), ('PROGRESS', 'В обработке'), ('SUCCESS', 'Успешно завершена'), ('FAILURE', 'Ошибка выполнения')], default='PENDING', max_length=20, verbose_name='Статус задачи')),
                ('processor_type', models.CharField(blank=True, choices=[('smeta_ru', 'Смета ру'), ('grand_smeta', 'Грандсмета'), ('turbosmetchik', 'Турбосметчик')], max_length=50, null=True, verbose_name='Тип обработчика')),
                ('sub_processor_type', models.CharField(blank=True, choices=[('type1', 'Тип 1 для Турбосметчика'), ('type2', 'Тип 2 для Турбосметчика'), ('type3', 'Тип 3 для Турбосметчика'), ('N/A', 'Не применимо / Не выбрано')], default='N/A', max_length=50, null=True, verbose_name='Подтип обработчика (если применимо)')),
                ('progress_info', models.JSONField(blank=True, null=True, verbose_name='Информация о прогрессе')),
                ('result_message', models.TextField(blank=True, null=True, verbose_name='Сообщение о результате')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
            ],
            options={
                'verbose_name': 'Задача обработки',
                'verbose_name_plural': 'Задачи обработки',
                'ordering': ['-created_at'],
            },
        ),
    ]
